print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/kalford/Documents/Projects/tf_client/Assets/Visual Effects/Models/buzzsaw.mb"`)
{		
	file -o "/Users/kalford/Documents/Projects/tf_client/Assets/Visual Effects/Models/buzzsaw.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/kalford/Documents/Projects/tf_client/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/kalford/Documents/Projects/tf_client/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/kalford/Documents/Projects/tf_client/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
